export const doctors = [
  {
    id: "1",
    name: "Dr. Arjun Mehta",
    qualification: "MBBS, MD (Cardiology)",
    address: "123 MG Road, Indiranagar, Bangalore, Karnataka",
    subSpecialisation: "Cardiology",
    email: "arjun.mehta@example.com",
    phone: "9876543210",
    photo: "/placeholder.svg?height=200&width=300",
    "koa-profile": "http://localhost:3000",
    website: "http://www.google.com",
  },
  {
    id: "2",
    name: "Dr. Priya Sharma",
    qualification: "MBBS, MD (Dermatology)",
    address: "456 Koramangala Main Road, Bangalore, Karnataka",
    subSpecialisation: "Dermatology",
    email: "priya.sharma@example.com",
    phone: "9876543211",
    photo: "/placeholder.svg?height=200&width=300",
    "koa-profile": "http://localhost:3000",
    website: "http://www.google.com",
  },
  {
    id: "3",
    name: "Dr. Rajesh Kumar",
    qualification: "MBBS, DM (Neurology)",
    address: "789 HSR Layout, Bangalore, Karnataka",
    subSpecialisation: "Neurology",
    email: "rajesh.kumar@example.com",
    phone: "9876543212",
    photo: "/placeholder.svg?height=200&width=300",
    "koa-profile": "http://localhost:3000",
    website: "http://www.google.com",
  },
  {
    id: "4",
    name: "Dr. Sneha Patel",
    qualification: "MBBS, MS, DNB (Gynaecology)",
    address: "101 Whitefield Main Road, Bangalore, Karnataka",
    subSpecialisation: "Gynaecology",
    email: "sneha.patel@example.com",
    phone: "9876543213",
    photo: "/placeholder.svg?height=200&width=300",
    "koa-profile": "http://localhost:3000",
    website: "http://www.google.com",
  },
  {
    id: "5",
    name: "Dr. Vikram Singh",
    qualification: "MBBS, MD (Cardiology)",
    address: "202 Jayanagar 4th Block, Bangalore, Karnataka",
    subSpecialisation: "Cardiology",
    email: "vikram.singh@example.com",
    phone: "9876543214",
    photo: "/placeholder.svg?height=200&width=300",
    "koa-profile": "http://localhost:3000",
    website: "http://www.google.com",
  },
  {
    id: "6",
    name: "Dr. Ananya Reddy",
    qualification: "MBBS, MD (Dermatology)",
    address: "303 JP Nagar, Bangalore, Karnataka",
    subSpecialisation: "Dermatology",
    email: "ananya.reddy@example.com",
    phone: "9876543215",
    photo: "/placeholder.svg?height=200&width=300",
    "koa-profile": "http://localhost:3000",
    website: "http://www.google.com",
  },
  {
    id: "7",
    name: "Dr. Karthik Menon",
    qualification: "MBBS, DM (Neurology)",
    address: "404 Malleshwaram, Bangalore, Karnataka",
    subSpecialisation: "Neurology",
    email: "karthik.menon@example.com",
    phone: "9876543216",
    photo: "/placeholder.svg?height=200&width=300",
    "koa-profile": "http://localhost:3000",
    website: "http://www.google.com",
  },
  {
    id: "8",
    name: "Dr. Meera Iyer",
    qualification: "MBBS, MS (Gynaecology)",
    address: "505 Richmond Road, Bangalore, Karnataka",
    subSpecialisation: "Gynaecology",
    email: "meera.iyer@example.com",
    phone: "9876543217",
    photo: "/placeholder.svg?height=200&width=300",
    "koa-profile": "http://localhost:3000",
    website: "http://www.google.com",
  },
  {
    id: "9",
    name: "Dr. Sanjay Gupta",
    qualification: "MBBS, MD, DM (Cardiology)",
    address: "606 Bannerghatta Road, Bangalore, Karnataka",
    subSpecialisation: "Cardiology",
    email: "sanjay.gupta@example.com",
    phone: "9876543218",
    photo: "/placeholder.svg?height=200&width=300",
    "koa-profile": "http://localhost:3000",
    website: "http://www.google.com",
  },
  {
    id: "10",
    name: "Dr. Divya Nair",
    qualification: "MBBS, MD (Dermatology)",
    address: "707 Electronic City, Bangalore, Karnataka",
    subSpecialisation: "Dermatology",
    email: "divya.nair@example.com",
    phone: "9876543219",
    photo: "/placeholder.svg?height=200&width=300",
    "koa-profile": "http://localhost:3000",
    website: "http://www.google.com",
  },
  {
    id: "11",
    name: "Dr. Aditya Verma",
    qualification: "MBBS, DM (Neurology)",
    address: "808 Yelahanka, Bangalore, Karnataka",
    subSpecialisation: "Neurology",
    email: "aditya.verma@example.com",
    phone: "9876543220",
    photo: "/placeholder.svg?height=200&width=300",
    "koa-profile": "http://localhost:3000",
    website: "http://www.google.com",
  },
  {
    id: "12",
    name: "Dr. Lakshmi Rao",
    qualification: "MBBS, MS, DNB (Gynaecology)",
    address: "909 Marathahalli, Bangalore, Karnataka",
    subSpecialisation: "Gynaecology",
    email: "lakshmi.rao@example.com",
    phone: "9876543221",
    photo: "/placeholder.svg?height=200&width=300",
    "koa-profile": "http://localhost:3000",
    website: "http://www.google.com",
  },
  {
    id: "13",
    name: "Dr. Nikhil Joshi",
    qualification: "MBBS, MD (Cardiology)",
    address: "1010 Hebbal, Bangalore, Karnataka",
    subSpecialisation: "Cardiology",
    email: "nikhil.joshi@example.com",
    phone: "9876543222",
    photo: "/placeholder.svg?height=200&width=300",
    "koa-profile": "http://localhost:3000",
    website: "http://www.google.com",
  },
]
